---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'i=0; while true; do echo "$((i++)) | output text" >> /output/output.txt; sleep 5s; done']
          volumeMounts:
            - name: volume-1
              mountPath: /output
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: volume-1
              mountPath: /input
          env:
            - name: HTTP_PORT
              value: "1080"
            - name: HTTPS_PORT
              value: "10443"
      volumes:
        - name: volume-1
          persistentVolumeClaim:
            claimName: pvc-1
