---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  labels:
    app: nfs
  namespace: default
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.13.252
  share: /nfs-1
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
